# Generated by Django 5.0.6 on 2024-07-19 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('editorial', models.CharField(max_length=150)),
                ('autor', models.CharField(max_length=150)),
                ('genero', models.CharField(max_length=150)),
                ('cantidad_stock', models.IntegerField()),
                ('cantidad_hojas', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(upload_to='comics_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Figuras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(upload_to='figuras_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('editorial', models.CharField(max_length=150)),
                ('autor', models.CharField(max_length=150)),
                ('genero', models.CharField(max_length=150)),
                ('cantidad_stock', models.IntegerField()),
                ('cantidad_hojas', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(upload_to='libros_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Mangas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tomo', models.IntegerField()),
                ('editorial', models.CharField(max_length=150)),
                ('autor', models.CharField(max_length=150)),
                ('demografia', models.CharField(max_length=150)),
                ('cantidad_stock', models.IntegerField()),
                ('cantidad_hojas', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(upload_to='mangas_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
