# Generated by Django 5.0.6 on 2024-07-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('editorial', models.CharField(max_length=150)),
                ('autor', models.CharField(max_length=150)),
                ('genero', models.CharField(max_length=150)),
                ('cantidad_stock', models.IntegerField()),
                ('cantidad_hojas', models.IntegerField()),
            ],
        ),
    ]
